title: 'Samuel.pro'
description: "Just Another... wait ¿Jekyll? site"
baseurl: ""
url: "https://metac0m.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown

theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag
